version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:17.4
        environment:
          TZ: "America/Sao_Paulo"
    steps:
      - checkout
      - run: npm install
      - run: COVERALLS_GIT_BRANCH=$CIRCLE_BRANCH npm run check

workflows:
  build:
    jobs:
      - test
